{{- if .Values.rpaas.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    tsuru.io/pool: {{ .Values.tsuru.pool.name }}
    {{- include "..labels" . | nindent 4 }}
  name: tsuru-rpaas-slis
spec:
{{- if .Values.tickets.enabled }}
{{ .Files.Get "files/rules/tsuru-rpaas-slis.yaml" | indent 2 }}
{{- else }}
{{ .Files.Get "files/rules/tsuru-rpaas-slis-light.yaml" | indent 2 }}
{{- end }}
{{- end }}
