# Default values for tsuru-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tsuruRules:
  labels: {}
  annotations: {}

tickets:
  enabled: true

rpaas:
  enabled: true
  namespaceSelector: {}
  selector: {}

nginx:
  enabled: true

remoteRead:
  enabled: false
  readers: []
  # - apiGroup: rbac.authorization.k8s.io
  #   kind: User
  #   name: my-user

nodeLocalDNS:
  enabled: false
  # podMonitorLabels: {}

calicoNode:
  enabled: false
  # podMonitorLabels: {}
  port: "9099"
