{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{  include "acl-operator.fullname" .}}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "acl-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- include "acl-operator.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
{{- end }}
