{{- if .Values.metricsScaling.enabled }}
{{- $namespace := .Values.metricsScaling.prometheus.namespace }}
{{- $query := .Values.metricsScaling.prometheus.query }}
{{- if $namespace }}
{{- $query = printf "(sum(deploy_agent_builds_waiting_for_lease{exported_namespace=\"%s\"}) or vector(0)) + (sum(deploy_agent_builds_active{exported_namespace=\"%s\"}) or vector(0))" $namespace $namespace }}
{{- end }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
{{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}
  name: {{ include "buildkit.fullname" . }}
  labels:
    {{- include "buildkit.labels" . | nindent 4 }}
spec:
  cooldownPeriod: {{ .Values.metricsScaling.cooldownPeriod }}
  idleReplicaCount: {{ .Values.metricsScaling.idleReplicaCount }}
  maxReplicaCount: {{ .Values.metricsScaling.maxReplicaCount }}
  minReplicaCount: {{ .Values.metricsScaling.minReplicaCount }}
  pollingInterval: {{ .Values.metricsScaling.pollingInterval }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ include "buildkit.fullname" . }}
  triggers:
  - metadata:
      query: {{ $query | quote }}
      serverAddress: {{ .Values.metricsScaling.prometheus.serverAddress | quote }}
      threshold: {{ .Values.metricsScaling.prometheus.threshold | quote }}
    type: prometheus
{{- end }}
