apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItdHN1cnUuYXJ0aWZhY3RvcnkuZ2xvYm9pLmNvbSI6eyJ1c2VybmFtZSI6InRzdXJ1X2FwcCIsInBhc3N3b3JkIjoiVHN1cnViMi00YWMiLCJhdXRoIjoiZEhOMWNuVmZZWEJ3T2xSemRYSjFZakl0TkdGaiJ9fSwiY3JlZEhlbHBlcnMiOnsic291dGhhbWVyaWNhLWVhc3QxLWRvY2tlci5wa2cuZGV2IjoiZ2NyIiwidXMtZWFzdDEtZG9ja2VyLnBrZy5kZXYiOiJnY3IifX0=
kind: Secret
metadata:
  name: docker-config-tsuru
  namespace: tsuru-system
type: kubernetes.io/dockerconfigjson
