{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rate-limit-control-plane.fullname" . }}
  labels:
    {{- include "rate-limit-control-plane.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "rate-limit-control-plane.selectorLabels" . | nindent 6 }}
{{- end }}
