{{- if .Values.deployAgent.dockerConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy-agent.dockerConfigName" . }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {{- .Values.deployAgent.dockerConfig | nindent 4 }}
{{- end }}
